### PR TITLE
update app link to query for local-cluster

### PR DESCRIPTION
**Pull request by RobDolares**
Signed-off-by: rhowingt@redhat.com <rhowingt@redhat.com>

**Related Issue:**  https://github.com/open-cluster-management/backlog/issues/14540

### Description of changes
Update overview summary link for applications to account for local-cluster only.

### CODE REVIEW

**Review by KevinFCormier — CHANGES_REQUESTED** [review]
The `buildSumaryLinks` appears to be used for nodes and pods as well. Will the numbers shown on the Overview page for these match what is returned in search results after this change?

**Comment by RobDolares** [comment]
> The `buildSumaryLinks` appears to be used for nodes and pods as well. Will the numbers shown on the Overview page for these match what is returned in search results after this change?

@KevinFCormier - Actually no - so that is current issue.  Should we remove the `local-cluster` label from applications?

**Comment by KevinFCormier** [comment]
> > The `buildSumaryLinks` appears to be used for nodes and pods as well. Will the numbers shown on the Overview page for these match what is returned in search results after this change?
> 
> @KevinFCormier - Actually no - so that is current issue. Should we remove the `local-cluster` label from applications query?

For the displayed count of applications, you got it by counting ACM applications and Argo applications that are on the hub, right? So if the search link does not specify the cluster, it would include Argo applications defined on remote clusters. (Both ACM and Argo applications currently use the kind application with different API groups.)

**Review by KevinFCormier — APPROVED** [review]
Looks good!

**Pull request merged**
