### PR TITLE
[release 2.2] update kubernetes/client-node

### PR DESCRIPTION
**Pull request by SherinV**
**Related Issue:**  open-cluster-management/backlog#10977

### Description of changes
- Updated package version

### CODE REVIEW

**Comment by SherinV** [comment]
@jlpadilla Please review package update for 2.2 branch.

**Review by jlpadilla — APPROVED** [review]

**Comment by SherinV** [comment]
Reverted changes as 2.2.2 is closed. Will merge to 2.2.3 when it opens

**Pull request merged**
