### PR TITLE
Update modals for consistency & update ui-components version

### PR DESCRIPTION
**Pull request by zlayne**
Signed-off-by: Zack Layne <zlayne@redhat.com>

**Related Issue:**  open-cluster-management/backlog#13026

### Description of changes
- Updated UI-components version
- Updated all modals for consistency (see below) FYI @richiepiya 

Screen Shot 2021-06-22 at 2 26 20 PM
Screen Shot 2021-06-22 at 2 26 29 PM
Screen Shot 2021-06-22 at 2 26 37 PM
Screen Shot 2021-06-22 at 2 26 44 PM
Screen Shot 2021-06-22 at 2 26 55 PM

### CODE REVIEW

**Comment by richiepiya** [comment]
Would it be possible to remove the "Info" icons? At the moment, we only want to keep the "Warning" icons in the modals for irreversible actions of consequence (like delete or detach).

Also, why is deleting a saved search deleting all pods here?
Screen Shot 2021-06-22 at 2 45 24 PM

**Comment by zlayne** [comment]
I will remove the info icon from the Search guide & share search modals.
The save search modal either saves or edits a user define saved search - wasnt sure if that counted as a consequence of an action. but I can remove it no problem.
`All pods` is the name of the saved search. It isnt actually deleting any pods just the user defined saved search :)

**Comment by richiepiya** [comment]
- Right, then yeah I don't think the save search needs a "Warning" icon since it can be edited.
- Ahh okay makes sense! This is more of a question for docs but would something like this be more clear? `Are you sure that you want to delete the saved search: All pods?`
Thanks!

**Comment by zlayne** [comment]
> * Right, then yeah I don't think the save search needs a "Warning" icon since it can be edited.
> * Ahh okay makes sense! This is more of a question for docs but would something like this be more clear? `Are you sure that you want to delete the saved search: All pods?`
>   Thanks!

That might be a bit clearer, was going with the same text OCP is using.

**Review by jlpadilla — APPROVED** [review]
/lgtm

**Pull request merged**
